# fly.toml app configuration file generated for omniquiz on 2023-05-23T20:50:58-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "omniquiz"
primary_region = "sjc"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
